#! /bin/bash

cd ~/.config/bspwm
. ./monitors

compton --config ~/.compton.conf -b
feh --bg-scale ~/wallpapers/wallpaper.png
bspc config border_width 0
bspc config window_gap 10
bspc config click_to_focus true
bspc monitor $MONITOR_RIGHT -d terminal files games
bspc monitor $MONITOR_LEFT -d www mail misc

bspc desktop games -t state=floating
bspc rule -a keepassx state=floating
bspc rule -a Keepassx state=floating
bspc rule -a KeePass2 state=floating
bspc rule -a Steam state=floating

bspc rule -a UXTerm desktop=terminal
bspc rule -a Firefox desktop=www
bspc rule -a Iceweasel desktop=www
bspc rule -a Google-chrome-stable desktop=www
bspc rule -a google-chrome desktop=www
bspc rule -a Google-chrome desktop=www
bspc rule -a Thunderbird desktop=mail
bspc rule -a Nemo desktop=files
bspc rule -a Steam desktop=games

dunst -geometry "0x10-0+$PANEL_HEIGHT" &

./panel &
redshift-gtk &

cd ~

uxterm tmux &
google-chrome-stable &
thunderbird &
sleep 5 && nemo &> /dev/null &
export _JAVA_AWT_WM_NONREPARENTING=1
