#! /bin/bash

compton --config ~/.compton.conf -b
feh --bg-scale ~/wallpapers/wallpaper.png
bspc config border_width 0
bspc config window_gap 10
bspc monitor DFP9  -d terminal files games
bspc monitor DFP10 -d www mail misc

bspc desktop games -t state=floating
bspc rule -a keepassx state=floating
bspc rule -a KeePass2 state=floating
bspc rule -a Steam state=floating

bspc rule -a xterm desktop=terminal
bspc rule -a Firefox desktop=www
bspc rule -a Iceweasel desktop=www
bspc rule -a Google-chrome-stable desktop=www
bspc rule -a Thunderbird desktop=mail
bspc rule -a Nemo desktop=files
bspc rule -a Steam desktop=games

dunst -geometry "0x10-0+$PANEL_HEIGHT" &

cd ~/.config/bspwm
./panel &
redshift-gtk &

cd ~

uxterm tmux &
google-chrome-stable &
thunderbird-bin &
sleep 5 && nemo &> /dev/null &
