#! /bin/bash

PANEL_FIFO="/tmp/panel_fifo"
PANEL_FIFO2="/tmp/panel_fifo2"
PANEL_HEIGHT=20
FONT_FAMILY="DejaVu Sans Mono For Powerline:14"

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

bspc config top_padding 30

[ -e "$PANEL_FIFO"  ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"
[ -e "$PANEL_FIFO2"  ] && rm "$PANEL_FIFO2"
mkfifo "$PANEL_FIFO2"

bspc control --subscribe > "$PANEL_FIFO2" &
while true; do echo 'S\n' > "$PANEL_FIFO2" ;sleep 20; done &
xtitle -sf 'T\n' > "$PANEL_FIFO2" &

bspc control --subscribe > "$PANEL_FIFO" &
while true; do echo 'S\n' > "$PANEL_FIFO" ;sleep 20; done &
xtitle -sf 'T\n' > "$PANEL_FIFO" &

dunst -geometry "0x10-0+$PANEL_HEIGHT" &

. ./panel_colors
. ./monitors

trayer --edge top --align right --distance 7 --margin 10 --widthtype request --height $PANEL_HEIGHT --tint "$COLOR_BACKGROUND" --transparent true &

cat "$PANEL_FIFO"                                                                       \
| ./panel_bar $MONITOR_LEFT                                                                     \
| lemonbar -g 1900x$PANEL_HEIGHT+10+7 -u 2 -f "$FONT_FAMILY" -F "$COLOR_FOREGROUND" -B "$COLOR_BACKGROUND" \
| while read line; do eval "$line"; done &
wait&

cat "$PANEL_FIFO2"                                                                       \
| ./panel_bar $MONITOR_RIGHT                                                                       \
| lemonbar -g 1900x$PANEL_HEIGHT+1930+7 -u 2 -f "$FONT_FAMILY" -F "$COLOR_FOREGROUND" -B "$COLOR_BACKGROUND" \
| while read line; do eval "$line"; done &

wid=$(xdo id -a "bar")
tries_left=20
while [ -z "$wid" -a "$tries_left" -gt 0  ] ; do
    sleep 0.5
    wid=$(xdo id -a "bar")
    tries_left=$((tries_left - 1))
done
[ -n "$wid"  ] && for window in $wid ; do
    xdo above -t "$(xdo id -N Bspwm -n root | sort | head -n 1)" "$window"
done

wait
