#! /bin/sh

PATH=$PATH:~/Projects/bar-widgets
. ./panel_colors

while read -r line ; do
    clock=`date "+%a %b %d %R"`
    active_win=`bspinfo -w -a`
    output=''
    for monitor in $1 ; do
        if [ $monitor = "DFP9" ];then
            output="${output}%{l}%{S1}"
        elif [ $monitor = "DFP10" ];then
            output="${output}%{l}%{S0}"
        fi
        # check if current monitor is the active one
        bspinfo -a $monitor
        if [ $? -eq 0 ]; then
            output="${output}%{F$COLOR_ACTIVE_MONITOR_FG}%{B$COLOR_ACTIVE_MONITOR_BG}"
        else
            output="${output}%{F$COLOR_INACTIVE_MONITOR_FG}%{B$COLOR_INACTIVE_MONITOR_BG}"
        fi
        output="${output} ${clock} %{B-}%{F-}"
        for desktop in $(bspinfo -d -m $monitor) ; do
            name=${desktop#?}
            case $desktop in
                O*)
                    # focused occupied desktop
                    output="${output}%{A:bspc desktop -f ${name}:}%{F$COLOR_FOCUSED_OCCUPIED_FG}%{B$COLOR_FOCUSED_OCCUPIED_BG}%{U$COLOR_UNDERLINE}%{+u} ${name} %{-u}%{U-}%{B-}%{F-}%{A}"
                    windows=`bspinfo -w -d "$name"`
                    ;;
                F*)
                    # focused free desktop
                    output="${output}%{A:bspc desktop -f ${name}:}%{F$COLOR_FOCUSED_FREE_FG}%{B$COLOR_FOCUSED_FREE_BG}%{U$COLOR_UNDERLINE}%{+u} ${name} %{-u}%{U-}%{B-}%{F-}%{A}"
                    windows=`bspinfo -w -d "$name"`
                    ;;
                U*)
                    # focused urgent desktop
                    output="${output}%{A:bspc desktop -f ${name}:}%{F$COLOR_FOCUSED_URGENT_FG}%{B$COLOR_FOCUSED_URGENT_BG}%{U$COLOR_UNDERLINE}%{+u} ${name} %{-u}%{U-}%{B-}%{F-}%{A}"
                    windows=`bspinfo -w -d "$name"`
                    ;;
                o*)
                    # occupied desktop
                    output="${output}%{A:bspc desktop -f ${name}:}%{F$COLOR_OCCUPIED_FG}%{B$COLOR_OCCUPIED_BG} ${name} %{B-}%{F-}%{A}"
                    ;;
                f*)
                    # free desktop
                    output="${output}%{A:bspc desktop -f ${name}:}%{F$COLOR_FREE_FG}%{B$COLOR_FREE_BG} ${name} %{B-}%{F-}%{A}"
                    ;;
                u*)
                    # urgent desktop
                    output="${output}%{A:bspc desktop -f ${name}:}%{F$COLOR_URGENT_FG}%{B$COLOR_URGENT_BG} ${name} %{B-}%{F-}%{A}"
                    ;;
            esac
        done
        output="${output}%{c}"
        num_win=`echo "$windows"|wc -l`
        for window in $windows ; do
            window_name=`xtitle -t $((50 / $num_win)) "$window"`
            if [ "$window" = "$active_win" ]; then
                output="${output}%{A:bspc node -f ${window}:}%{U$COLOR_UNDERLINE}%{+u} ${window_name} %{-u}%{U-}%{A}"
            else
                output="${output}%{A:bspc node -f ${window}:} ${window_name} %{A}"
            fi
        done
    done
    printf "%s\n" "${output}"
done
